class ServiceImport
	def self.import
	  ActiveRecord::Base.connection.insert("INSERT INTO services (name_en, name_ru, name_es, service_type_id) 
	    VALUES ('Vehicle Health Check', 'Проверка работоспособности автомобиля', 'cheque de coche', 1),
	    ('Pre MOT Checks', 'Проверка перед техосмотром', 'Inspección antes de la inspección técnica', 1),
	    ('MOT Partner Service', 'Партнерская программа по техосмотру', 'Programa de afiliados para la inspección técnica', 1),
	    ('Puncture Repair', 'Ремонт прокола покрышки', 'Reparación de pinchazos de neumáticos', 2),
	    ('Tyre Pressure Monitoring System', 'Контроль давления в шинах', 'Monitoreo de presión de llantas', 2),
	    ('Nitrogen Inflation', 'Накачивание шин азотом', 'Neumático de nitrógeno inflado', 2),
	    ('Wheel Balancing', 'Балансировка колёс', 'Balanceo de ruedas', 2),
	    ('Environmental Tyre Disposal', 'Утилизация шин', 'Reciclaje de llantas', 2),
	    ('Tyre Clearance Event', 'Замер клиренса автомобиля', 'Medición de la liquidación del vehículo', 2),
	    ('Tyre Labelling', 'Определение типа шин', 'Determinación del tipo de neumático', 2),
	    ('Check Tire Tread Depth', 'Проверка износа шин', 'Inspección del desgaste de los neumáticos', 2),
	    ('Finding Your Tyre Size', 'Подбор шин', 'Selección de neumáticos', 2),
	    ('Winter Bundle', 'Замена на зимний комплект шин', 'Sustitución de los neumáticos de invierno', 2),
	    ('Front Axle Computer Alignment', 'Выравнивание передних колес с помощью компьютера', 'Alinea las ruedas delanteras con un ordenador', 2),
	    ('Front & Rear Computerised Wheel Alignment', 'Компьютеризированное выравнивание передних и задних  колёс', 'Alineación computarizada de las ruedas delanteras y traseras', 2),
	    ('Standard Wheel Alignment', 'Стандартное выравнивание колес', 'Alineación de ruedas estándar', 2),
	    ('Wheel bearings checked', 'Проверка колесных подшипников', 'Control de rodamiento de rueda', 2),
	    ('Plug tyres', 'Установка колёс', 'Instalación de ruedas', 2),
	    ('Air Conditioning Recharge', 'Перезарядка кондиционера', 'Recargando el aire acondicionado', 3),
	    ('Air Conditioning Anti-bacterial Clean', 'Антибактериальная очистка кондиционера', 'Limpieza antibacteriana del aire acondicionado', 3),
	    ('Air Conditioning Anti-bacterial Clean & Recharge', 'Антибактериальная очистка и перезарядка кондиционера', 'Limpieza antibacteriana y recarga del aire acondicionado', 3),
	    ('Suspension checked', 'Проверка подвески', 'Control de suspensión', 3),
	    ('Suspension Repair', 'Ремонт подвески', 'Reparación de la suspensión', 3),
	    ('Brake Inspection', 'Проверка тормозов', 'Control de frenos', 3),
	    ('Brake Fluid Change', 'Замена тормозной жидкости', 'Reemplazo de líquido de frenos', 3),
	    ('Brake discs replacement', 'Замена тормозных дисков', 'Reemplazo de discos de freno', 3),
	    ('Handbrake operation checked', 'Проверка работы ручного тормоза', 'Control de freno de mano', 3),
	    ('Change car Batteries', 'Замена аккумулятора', 'Reemplazo de la batería', 3),
	    ('Free Battery Check', 'Бесплатная проверка аккумулятора', 'Comprobación de la batería gratis', 3),
	    ('Engine Diagnostics', 'Диагностика двигателя', 'Diagnóstico del motor', 3),
	    ('Checks steering system and driveshaft', 'Проверка системы рулевого управления', 'Compruebe el sistema de dirección', 3),
	    ('Exhaust system checked', 'Проверка выхлопной системы', 'Comprobación del sistema de escape', 3),
	    ('Exhaust Fitting', 'Установка выхлопной системы', 'Instalación del sistema de escape', 3),
	    ('Clutch operation checked', 'Проверка сцепления', 'Control de embrague', 3),
	    ('Clutch Repair', 'Ремонт сцепления', 'Reparación de embrague', 3),
	    ('Clutch - Assembly', 'Сцепление - сборка', 'Acoplamiento - montaje', 3),
	    ('Reset service light', 'Сброс ошибок через компьютер', 'Restablecer errores vía computadora', 3),
	    ('Computer Diagnostics', 'Компьютерная диагностика', 'Diagnóstico computacional', 3),
	    ('Cambelt Replacement', 'Замена ГРМ', 'Reemplazo de tiempo', 3),
	    ('Steering Repair', 'Ремонт рулевого управления', 'Reparación de la dirección', 3),
	    ('Air Filter Replacement', 'Замена воздушного фильтра', 'Reemplazo del filtro de aire', 3),
	    ('Oil change in transmission', 'Замена масла в коробке передач', 'Gearbox oil change', 3),
	    ('Replacing the engine oil and oil filter', 'Замена моторного масла и масляного фильтра', 'Sustitución del aceite del motor y del filtro de aceite', 3),
	    ('Removing water from the fuel filter', 'Удаление воды из топливного фильтра', 'Eliminar el agua del filtro de combustible', 3),
	    ('Replacing the cabin filter', 'Замена салонного фильтра', 'Sustitución del filtro de cabina', 3),
	    ('Fuel filter replacement', 'Замена топливного фильтра', 'Reemplazo del filtro de combustible', 3),
	    ('Coolant/Antifreeze Change', 'Замена охлаждающей жидкости / антифриза', 'Reemplazo de refrigerante / anticongelante', 3),
	    ('Duxback - Windscreen', 'Duxback - ветровое стекло', 'Duxback - Parabrisas Duxback - parabrisas', 3),
	    ('Duxback - Front Glass', 'Duxback - переднее стекло', 'Duxback - Vidrio delantero Duxback - vidrio delantero', 3),
	    ('Duxback - Whole Car', 'Duxback - весь автомобиль', 'Duxback - Whole Car Duxback - todo el auto', 3),
	    ('DPF Maintenance Clean', 'Очистка сажевого фильтра', 'Limpieza de filtro de partículas', 3),
	    ('DPF Deep Clean', 'Глубокая очистка сажевого фильтра', 'Filtro de partículas de limpieza profunda', 3),
	    ('Cataclean®', 'Присадки для очистки двигателя', 'Aditivos de limpieza del motor', 3),
	    ('Radiator repair', 'Ремонт радиатора', 'Reparacion de radiadores', 3),
	    ('Radiator flush', 'Очистка радиатора', 'Limpieza del radiador', 3),
	    ('Removing stripped screws', 'Снятие зачищенных винтов', 'Extracción de los tornillos pelados', 3),
	    ('Free Safety Check', 'Бесплатная проверка безопасности', 'Control de seguridad gratuito', 3),
	    ('Headlight bulbs', 'Лампы для фар', 'Bombillas de los faros', 4),
	    ('Vehicle Bulbs', 'Автомобильные лампы', 'Lamparas de coche', 4),
	    ('Alternator', 'Генератор', 'Grupo electrógeno', 4),
	    ('Techron: Fuel System Cleaner', 'Очиститель топливной системы', 'Limpiador del sistema de combustible', 4),
	    ('AdBlue', 'Средство для снижения выбросов оксидов азота дизельных двигателей', 'Medios para reducir las emisiones de óxidos de nitrógeno de los motores diesel', 4),
	    ('Cylinder Head Gasket', 'Прокладка головки блока цилиндров', 'Junta de culata', 4),
	    ('Water Pump', 'Помпа', 'Bomba', 4),
	    ('Alternator/Fan Belt', 'Ремень генератора / вентилятора', 'Correa del alternador / ventilador', 4),
	    ('Starter Motor', 'Стартер', 'Arrancador de motor', 4),
	    ('Clutch - Slave Cylinder', 'Сцепление - ведомый цилиндр', 'Acoplamiento - cilindro accionado', 4),
	    ('Drive Shaft', 'Приводной вал', 'Eje de accionamiento', 4),
	    ('Spark plugs', 'Свечи зажигания', 'Bujias de encendido', 4),
	    ('Fuel gauge sender', 'Датчик уровня топлива', 'Sensor de nivel de combustible', 4),
	    ('ABS sensors', 'Датчики ABS', 'Sensores ABS', 4),
	    ('Radiator hoses', 'Шланг радиатора', 'Manguera del radiador', 4),
	    ('Blown fuses', 'Предохранители', 'Fusibles', 4),
	    ('Car Signal Relays', 'Реле', 'Relé', 4),
	    ('windshield wipers', 'Дворники', 'Conserjes', 4),
	    ('Dangling exhaust pipes', 'Выхлопные трубы', 'Tubos de escape', 4),
	    ('Fuel Filters', 'Топливные фильтры', 'Filtros de combustible', 4),
	    ('Window belt strips', 'Околооконные уплотнительные резинки', 'Cerca de las bandas de sellado de la ventana', 4),
	    ('Seat belts and seatbelt retractors', 'Ремни безопасности', 'Cinturones de seguridad', 4),
		  ('Serpentine belts', 'Ручейковый ремень', 'Correa trapezoidal', 4),        
	    ('Thermostats', 'Термостаты', 'Termostatos', 4),
	    ('Washer tanks', 'Бочок для омывающей жидкости', 'Barril para lavado de fluidos', 4),
	    ('Clean Tires, Rims and Fender Wells', 'Чистка шин, ободов и крыльев', 'Limpieza de llantas, llantas y alas', 5),
	    ('Clean Windows', 'Чистка окон', 'Limpieza de ventanas', 5),
	    ('Vacuum Interior', 'Очистка салона с помощью пылесоса', 'Limpieza del interior con una aspiradora', 5),
	    ('Shampoo Seats and Carpets', 'Мойка сидений и ковриков', 'Lavado de asientos y alfombras', 5),
	    ('Polishing', 'Полировка', 'Pulido', 5),
	    ('Waxing', 'Нанесение воска', 'Depilación', 5),
	    ('Steam Cleaning', 'Очистка паром', 'Limpieza a vapor', 5),
	    ('Stain Removal', 'Удаление пятен', 'Eliminación de manchas', 5),
	    ('Carpet Cleaning', 'Чистка ковриков', 'Alfombras de limpieza', 5),
	    ('Clean and Condition Leather', 'Чистка и восстановление кожи', 'Limpieza y restauración de la piel', 5),
	    ('Tar and Road Film Removal', 'Удаление смолы и дорожной пленки', 'Eliminación de alquitrán y road film', 5),
	    ('Upholstery Cleaning', 'Очистка обивки салона', 'Limpieza de tapiceria', 5),
	    ('Swirl & Scratch Removal', 'Удаление царапин и полировка', 'Rascar y pulir', 5),
	    ('Car Insurance', 'Страхование автомобиля', 'Seguro de coche', 6),
	    ('Black Box Car Insurance', 'Страхование автомобилей Black Box', 'Seguro de coche Black Box', 6),
	    ('Temporary Car Insurance', 'Временное страхование автомобиля', 'Seguro de coche temporal', 6),
	    ('Learner Driver Insurance', 'Страхование водителей-учеников', 'Seguro de conductores de estudiantes', 6),
	    ('Multicar Insurance', 'Страхование для нескольких автомобилей', 'Seguro para varios coches', 6),
	    ('Classic Car Insurance', 'Классическое страхование автомобиля', 'Seguro de coche clásico', 6),
	    ('Test Drive Insurance', 'Страхование на тест-драйва автомобиля', 'Seguro para un auto de prueba de manejo', 6),
	    ('Young & New Driver Insurance', 'Страхование молодых и новых водителей', 'Seguro de conductores jóvenes y nuevos', 6),
	    ('Commercial Motor Insurance', 'Страхование коммерческих автомобилей', 'Seguro de automóvil comercial', 6),
	    ('Motorbike Insurance', 'Страхование мотоциклов', 'Seguro de motos', 6),
	    ('Vehicle registration number', 'Регистрационный номер автомобиля', 'Número de registro del vehículo', 7),
	    ('Drivers license', 'Водительское удостоверение', 'Licencia de conducir', 7),
	    ('Other', 'Прочее', 'Otro', 3)");
	  puts "Services imported"
	end
end
